baseURL: "https://AndrewWu29.github.io/"
title: Andrew's Blog
paginate: 5
theme: PaperMod
defaultContentLanguage: en
disqusShortname: andrewwu29
# languageCode: zh-tw

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: "G-6L9D9LK7RB"

permalinks:
  posts: /:year/:month/:title/

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Andrew's Blog
  description: Loving to explore this world, sharing my thoughts 
  keywords: [Blog, Portfolio, PaperMod, Diary]
  author: Andrew Wu
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowFullTextinRSS: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #apple_touch_icon: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "Andrew's Blog"
    #icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  #profileMode:
  #  enabled: True # needs to be explicitly set
  #  title: Andrew Wu
  #  subtitle: "還在英國苦尋工作的軟體測試工程師"
  #  imageUrl: "profile_avatar_1.jpg"
  #  imageWidth: 150
  #  imageHeight: 150
    #imageTitle: my image
  #  buttons:
  #    - name: 貼文
  #      url: posts
  #    - name: 標籤
  #      url: tags
  #    - name: 分類
  #      url: categories

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/bing-ying-wu-3b71b783"
    - name: github
      url: "https://github.com/AndrewWu29"
    - name: email
      url: "mailto:ying.wu0129@gmail.com"
    - name: rss
      url: "index.xml"

  # home-info mode
  #homeInfoParams:
    #Title: "您好 \U0001F44B"
    #Content: 歡迎來到我的部落格

  #socialIcons:
    #- name: twitter
      #url: "https://twitter.com/"
    #- name: stackoverflow
      #url: "https://stackoverflow.com"
    #- name: github
      #url: "https://github.com/"

  #analytics:
    #google:
      #SiteVerificationTag: "XYZabc"
    #bing:
      #SiteVerificationTag: "XYZabc"
    #yandex:
      #SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
    DateFormat: "January 2, 2006"
    profileMode:
      enabled: true
      imageUrl: "profile_avatar.jpg"
      imageWidth: 180
      imageHeight: 180
      title: Andrew Wu
      subtitle: I'm a QAE, and seeking a job in the UK.
      buttons:
        - name: Posts
          url: posts
        - name: Tags
          url: tags
    menu:
      main:
        - identifier: posts
          name: Posts
          url: /posts/
          weight: 1
        - identifier: categories
          name: Categories
          url: /categories/
          weight: 2
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 3
        - identifier: search
          name: Search
          url: /search/
          weight: 4
        - identifier: about
          name: About
          url: /about/
          weight: 5
  zh-tw:
    contentDir: content/zh-tw
    languageName: 中文
    weight: 2
    DateFormat: "2006 January 2"
    profileMode:
      enabled: true
      imageUrl: "../profile_avatar.jpg"
      imageWidth: 180
      imageHeight: 180
      title: Andrew Wu
      subtitle: 還在英國尋找工作機會的軟體測試工程師
      buttons:
        - name: 貼文
          url: posts
        - name: 標籤
          url: tags
    label:
      text: 安德魯的部落格
    menu:
      main:
        - identifier: posts
          name: 文章
          url: posts
          weight: 1
        - identifier: categories
          name: 分類
          url: categories
          weight: 2
        - identifier: tags
          name: 標籤
          url: tags
          weight: 3
        - identifier: search
          name: 搜尋
          url: search
          weight: 4
        - identifier: about
          name: 關於我
          url: about
          weight: 5
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai