baseURL: "https://AndrewWu29.github.io/Andrew_Wu29/"
title: Andrew's Blog
paginate: 5
theme: PaperMod
defaultContentLanguage: zh-tw
languageCode: zh-tw

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

permalinks:
  posts: /:year/:month/:title/

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Andrew's Blog"
    #icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: True # needs to be explicitly set
    # title: ExampleSite
    subtitle: "還在英國苦尋工作的軟體測試工程師"
    imageUrl: "https://media-exp1.licdn.com/dms/image/D5635AQHOkxkoH2KIWQ/profile-framedphoto-shrink_400_400/0/1636395586487?e=1640703600&v=beta&t=4W2quMuD6ESWRTwqKBmY0LSohFq6cM6UWkNF9I9AyR0"
    imageWidth: 120
    imageHeight: 120
    #imageTitle: my image
    buttons:
      - name: 貼文
        url: posts
      - name: 標籤
        url: tags
      - name: 分類
        url: categories
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/bing-ying-wu-3b71b783"
    - name: github
      url: "https://github.com/AndrewWu29"
    - name: email
      url: "mailto:ying.wu0129@gmail.com"

  # home-info mode
  #homeInfoParams:
    #Title: "您好 \U0001F44B"
    #Content: 歡迎來到我的部落格

  #socialIcons:
    #- name: twitter
      #url: "https://twitter.com/"
    #- name: stackoverflow
      #url: "https://stackoverflow.com"
    #- name: github
      #url: "https://github.com/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
menu:
  main:
    - identifier: posts
      name: 文章
      url: /posts/
      weight: 10
    - identifier: categories
      name: 分類
      url: /categories/
      weight: 20
    - identifier: tags
      name: 標籤
      url: /tags/
      weight: 30
    - identifier: search
      name: 搜尋
      url: /search/
      weight: 40
    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai