# This is a basic workflow to help you get started with Actions

name: Cypress CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: Get Hugo
        run: wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.47.1/hugo_0.47.1_Linux-64bit.deb
      - name: Install Hugo
        run: sudo dpkg -i /tmp/hugo.deb
      - name: Link Hugo
        run: sudo ln /usr/local/bin/hugo /usr/local/bin/hugo-0.47.1
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm test
